//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HamroLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class bookreturn
    {
        public int Id { get; set; }
        public Nullable<int> loan_id { get; set; }
        public Nullable<System.DateTime> return_date { get; set; }
        public Nullable<System.DateTime> actual_return_date { get; set; }
        public string due_fine { get; set; }
    
        public virtual Loan Loan { get; set; }
    }
}
