//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HamroLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HamroLibraryDbEntities1 : DbContext
    {
        public HamroLibraryDbEntities1()
            : base("name=HamroLibraryDbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<author> authors { get; set; }
        public virtual DbSet<book> books { get; set; }
        public virtual DbSet<bookreturn> bookreturns { get; set; }
        public virtual DbSet<Loan> Loans { get; set; }
        public virtual DbSet<loanCharge> loanCharges { get; set; }
        public virtual DbSet<loanType> loanTypes { get; set; }
        public virtual DbSet<member> members { get; set; }
        public virtual DbSet<membertype> membertypes { get; set; }
        public virtual DbSet<publisher> publishers { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<userlog> userlogs { get; set; }
    }
}
