//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HamroLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HamroLibraryDbEntities2 : DbContext
    {
        public HamroLibraryDbEntities2()
            : base("name=HamroLibraryDbEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<author> authors { get; set; }
        public virtual DbSet<book> books { get; set; }
        public virtual DbSet<Loan_Issue> Loan_Issue { get; set; }
        public virtual DbSet<Loan_Return> Loan_Return { get; set; }
        public virtual DbSet<member> members { get; set; }
        public virtual DbSet<membertype> membertypes { get; set; }
        public virtual DbSet<publisher> publishers { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<userlog> userlogs { get; set; }
    }
}
